version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mase_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mase_network

  wordpress:
    image: wordpress:latest
    container_name: mase_wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/modern-admin-styler
    depends_on:
      - db
    networks:
      - mase_network

volumes:
  db_data:
  wordpress_data:

networks:
  mase_network:
    driver: bridge
