# MASE Agent Hooks Configuration v3.0
# Last Updated: 2025-01-18

hooks:
  # PRE-COMMIT HOOKS (Before making changes)
  pre_commit:
    before_file_create:
      enabled: true
      trigger: "beforeFileCreate"
      description: "Check file count and naming before creating new file"
    
    before_method_add:
      enabled: true
      trigger: "beforeMethodAdd"
      description: "Check method count before adding to class"
    
    before_dependency_add:
      enabled: false
      trigger: "beforeDependencyAdd"
      description: "Validate external dependencies"
  
  # VALIDATION HOOKS
  validation:
    validate_file_size:
      enabled: true
      description: "Warn when file approaches size limit"
      thresholds:
        info: 300
        warning: 400
        urgent: 450
        fail: 500
    
    validate_method_length:
      enabled: true
      description: "Keep methods focused and readable"
      thresholds:
        info: 30
        warning: 40
        urgent: 45
        fail: 50
    
    validate_complexity:
      enabled: true
      description: "Prevent complex, hard-to-test code"
      max_complexity: 10
      max_nesting: 4
      max_parameters: 5
    
    validate_security:
      enabled: true
      description: "Prevent security vulnerabilities"
      checks:
        - nonce_verification
        - capability_checks
        - input_sanitization
        - output_escaping
        - no_direct_sql
    
    validate_performance:
      enabled: true
      description: "Prevent performance issues"
      checks:
        - no_n_plus_one
        - caching_implemented
        - efficient_queries
        - memory_usage
    
    validate_naming:
      enabled: true
      description: "Maintain consistent naming conventions"
      conventions:
        php_classes: "MASE_PascalCase"
        php_methods: "snake_case"
        php_variables: "snake_case"
        php_constants: "SCREAMING_SNAKE_CASE"
        js_objects: "PascalCase"
        js_variables: "camelCase"
        css_classes: "kebab-case"
  
  # POST-COMMIT HOOKS (After making changes)
  post_commit:
    after_file_create:
      enabled: true
      trigger: "afterFileCreate"
      description: "Ensure completeness after file creation"
    
    after_method_add:
      enabled: true
      trigger: "afterMethodAdd"
      description: "Ensure method is properly integrated"
    
    after_feature_complete:
      enabled: true
      trigger: "afterFeatureComplete"
      description: "Ensure feature is production-ready"
    
    before_commit_checklist:
      enabled: true
      trigger: "manual"
      description: "Comprehensive pre-commit validation"
  
  # CONTINUOUS HOOKS
  continuous:
    monitor_file_count:
      enabled: true
      description: "Track project growth"
      max_files: 20
      warn_at: 15
      critical_at: 18
    
    monitor_dependencies:
      enabled: true
      description: "Track coupling between components"
      max_dependencies: 5
    
    monitor_performance:
      enabled: true
      description: "Track performance metrics"
      targets:
        css_generation: 100  # ms
        settings_save: 500   # ms
        page_load: 450       # ms
        memory_usage: 50     # MB
        cache_hit_rate: 80   # percent
    
    monitor_test_coverage:
      enabled: true
      description: "Ensure adequate testing"
      min_coverage: 70  # percent

# ALERT CONFIGURATION
alerts:
  architecture_limit_reached:
    enabled: true
    priority: "CRITICAL"
    action: "BLOCK_COMMIT"
  
  performance_degradation:
    enabled: true
    priority: "HIGH"
    threshold: 50  # percent increase
  
  security_vulnerability:
    enabled: true
    priority: "CRITICAL"
    action: "BLOCK_COMMIT"
  
  test_coverage_drop:
    enabled: true
    priority: "MEDIUM"
    threshold: 70  # percent

# THRESHOLDS
thresholds:
  file_size:
    info: 300
    warning: 400
    urgent: 450
    fail: 500
  
  method_length:
    info: 30
    warning: 40
    urgent: 45
    fail: 50
  
  complexity:
    max: 10
  
  nesting_depth:
    max: 4
  
  parameters:
    max: 5
  
  test_coverage:
    min: 70
  
  file_count:
    max: 20
    warn: 15
    critical: 18

# REPORTING
reporting:
  daily_report:
    enabled: true
    time: "18:00"
  
  weekly_report:
    enabled: true
    day: "Friday"
    time: "17:00"
  
  feature_complete_report:
    enabled: true
    auto_generate: true

# INTEGRATION
integration:
  git:
    pre_commit_hook: true
    pre_push_hook: true
  
  ci_cd:
    run_on_pr: true
    run_on_merge: true
  
  notifications:
    slack: false
    email: false
    console: true

# VERSION
version: "3.0.0"
last_updated: "2025-01-18"
